### ISSUE TITLE
The given assembly name was invalid.

### ISSUE THREAD

**Issue by KevinWGagel** [hematic/psTroubleshootWinRM#1]
Installed the module like this:
`Install-Module -Name psTroubleshootWinRM -Repository PSGallery`

Tried to use the example code when I received this error:
`Convert-WinrmError: C:\MyFiles\Find-WinRMErroringServers\Find-Servers.ps1:14:19
Line |
  14 |          $Result = Convert-WinrmError -server $server -thrown_error $_ …
     |                    ~~~~~~~~~~~~~~~~~~
     | The 'Convert-WinrmError' command was found in the module 'psTroubleshootWinRM', but the module could not be loaded due to the following error: [The given assembly name was invalid.] For more information, run        
     | 'Import-Module psTroubleshootWinRM'.`

Following the instructions for more information I ran this:
`import-module psTroubleshootWinRM
Import-Module: The given assembly name was invalid.`

The manuscript file (psTroubleshootWinRM.psd1) is including this:
`RootModule = '.\psBlackberryUEM.psm1'`

**Comment by hematic** [comment]
Well, thats embarassing.

To fix this you can either grab the newer version i just [uploaded](https://www.powershellgallery.com/packages/psTroubleshootWinRM/1.0.1), or you can replace that line with:

 RootModule = '.\psTroubleshootWinRM.psm1'

**Comment by KevinWGagel** [comment]
Thank you. I've installed it fresh. No more error. However, all it does is print a list starting with processing, gives the distinguished name of the computer it is processing and moves to the next one. It does not appear to be trying to do anything with the list of computers to check.

This is how I'm testing:
`$windows_servers = Get-ADComputer -Filter "Enabled -eq '$true' -and OperatingSystem -like '*server*'" -Property DNSHostName, LastLogonDate, Enabled, OperatingSystem, DistinguishedName
$credential = get-credential`

`$failures = New-Object -TypeName System.Collections.ArrayList
foreach($server in $windows_servers){
Write-Host "Processing $($Server)"`
`    Try{
        $result = Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock{
            $env:computername
        } -ErrorAction Stop
    }   Catch {
        $Result = Convert-WinrmError -server $server -thrown_error $_ -test_ping $true -test_dns $true
        $failures.add($result) | out-null
    }
}`

**Comment by hematic** [comment]
So i'm not sure what your level of familiarity is with Powershell, but if you used the sample code on the main page, thats not going to directly output anything for other than the servernames and potentially a message that there are no errors.

Any errors and their details will be inside the $failures arraylist.

**Comment by hematic** [comment]
Also, the way you are testing probably isnt going to work either.

$windows_servers = Get-ADComputer -Filter "Enabled -eq '$true' -and OperatingSystem -like '*server*'" -Property DNSHostName, LastLogonDate, Enabled, OperatingSystem, DistinguishedName

This will return you a list of objects.  You cant pass an object into the property of Computername for Invoke-Command. It needs to be the server name.
